### PR TITLE
cs: refactoring variables

### PR DESCRIPTION
**Pull request by RobinCK**
Code consistency
Sometimes var was used and sometimes const

### CODE REVIEW

**Comment by RobinCK** [comment]
@remy 
I think here [link](https://github.com/remy/nodemon/pull/1313/commits/c12208bf5a63154d7b25bf61607bf7575ad0da8d#diff-b2048f4188632273753b02bbcc2e31deL139) was a bug

**Comment by remy** [comment]
@stablebot back off please. I'll review this PR.

**Comment by remy** [comment]
IIRC node@6 doesn't need the `'use strict'` in the scripts? I'd like to include this PR in a general refactor release that also drops node@4 at the same time - which would allow me to drop the `'use strict'` in the files too. 

Just can't remember if that's right or not!

**Comment by RobinCK** [comment]
Yes you are right

**Comment by remy** [comment]
Gah. @stalebot! I'll re-open this and merge with the new linting rules in the coming weeks.

**Pull request closed without merging**
