### PR TITLE
fix: use platform-specific separator when augmenting PATH

### PR DESCRIPTION
**Pull request by lorenzodallavecchia**
Fixes: #1951

### CODE REVIEW

**Comment by lorenzodallavecchia** [comment]
The `--delay` test is also failing on `main`, with no changes since the last time it passed (odd).
I'm positive that the PR is not the cause.

**Comment by lorenzodallavecchia** [comment]
Apparently, 8 seconds is no longer enough for that test I increased the timeout to 12 seconds. It should work now.

**Comment by remy** [comment]
With random failing tests I tend to just re-run (just not on email much on Sunday). Nodemon has a lot of brittle-like tests that require lots of spinning plates, so these tests sometimes do just bork randomly.

**Comment by lorenzodallavecchia** [comment]
Thanks for attending to this PR @remy.
I know full well the pains of unstable tests...

The failing one is probably not time-related, as it completes in about 1 second on my computer, so a 30s timeout should be more than sufficient.

What should I do now? I don't think I can rerun tests myself.
No hurry: I'd like to know if I can do something.
Thanks.

**Comment by lorenzodallavecchia** [comment]
Superseded by #1981.

**Comment by stijnherreman** [comment]
I didn't notice you submitted a PR long before me, sorry! But your suggested fix has eventually made it into a release :)

**Comment by lorenzodallavecchia** [comment]
@stijnherreman, no worries! :)

**Pull request closed without merging**
