### PR TITLE
Update run.js to include exit code in crash log

### PR DESCRIPTION
**Pull request by EtzBetz**
In my opinion the crash log should include the exit code

### CODE REVIEW

**Comment by remy** [comment]
Why? It's great you've got an opinion but right now only you know what that is...

**Comment by EtzBetz** [comment]
Well when my application closes unexpectedly, I want to know why it closed.

**Comment by remy** [comment]
The exit code won't give you that. You'll see `1` the case that your program exited "unexpectedly" (rather than nodemon restarting due to change). There's no error exit code you'll see…

**Comment by EtzBetz** [comment]
I thought that `code` was the code that node exited with? Isn't there a way to get the exit code of node?

**Comment by remy** [comment]
`1` is the exit code from node...

**Comment by EtzBetz** [comment]
Not when I exit in node code myself

**Pull request closed without merging**
