### PR TITLE
fix: unicode extensions not supported

### PR DESCRIPTION
**Pull request by alice0meta**

### CODE REVIEW

**Comment by alice0meta** [comment]
Afaict this actually works just fine; one of the tests was faulty.

**Comment by remy** [comment]
Can you a) add a test for this change to support the issue, b) rebase the commit to use the contributing format?

Thanks, otherwise looks good. I've got a few PRs that I need to merge and need to look at why these tests are causing issues (and randomly failing).

**Comment by alice0meta** [comment]
I don't know how to do that. Please just use this. It's a seven-character fix.

**Comment by remy** [comment]
If you don't rebase it won't be released. Not because I don't want to
release it but because the release is based on the commit message.

**Comment by alice0meta** [comment]
Can you please just make the edit yourself then? I've tried. I don't know how to do this. It's only a seven-character fix.

**Comment by remy** [comment]
Or in fact, since you've only a single commit you should be able to amend
your commit and push force it back.

Note, if don't add a test, it's fine in this case, but if the code is later
refactored the bug could be reintroduced. A test on this would protect the
fix in the future, that's all.

**Comment by alice0meta** [comment]
I understand you're not willing to fix this bug. I've closed the issue.

**Comment by remy** [comment]
Tell me what I'm supposed to test against, and if I have time, I'll redo
the commit. Sorry, I'm busy with paid work too :)

I appreciate the PR but I'm just trying to help you get it live.

**Comment by alice0meta** [comment]
The fix - which replaces a simple regex with a slightly different simple regex - is precisely defined https://github.com/remy/nodemon/issues/769 . I understand that you're not willing to implement it.

**Comment by remy** [comment]
"Not willing" you're kidding right? I tried to help you, but this isn't a
paid project for me, so I commit time when *I want*.

Have a read: http://alistapart.com/article/the-high-price-of-free

I'm willing to help you, but I'll only redo this work when I have time.

**Comment by alice0meta** [comment]
I understand that you prefer spending time arguing on the internet to fixing simple bugs. I don't blame you. Arguing on the internet is fun. I understand that nodemon does not and will not support languages other than English.

**Comment by remy** [comment]
I've tried to help you to get this live. You refuse to use the contributing guide. This change literally won't go live because the commit message is wrong. I'm not arguing, I'm replying on my phone, *trying* to help you get this live.

**Comment by alice0meta** [comment]
I haven't done this before. I don't know how to use this complicated system. I understand that the maintainers of nodemon do not and will not support languages other than English.

**Comment by remy** [comment]
Right. How about we start again. Let's be friends. I am the maintainer of nodemon.

I want to help you. Honestly.

Your commit is great because it adds support (I believe) for non English characters in filenames. :+1:

So, the problems *we* need to fix are:

1. The commit message won't trigger a build
2. We don't have any tests protecting your change from regression

You don't know how to do these things. Fair enough, if you'll let me teach you, then *we* can get your fix live, and you'll have made nodemon better for non-english filenames.

How does that sound?

**Comment by alice0meta** [comment]
That sounds like it would take much more time for both of us than you typing seven characters. You've typed a lot more than seven characters already, and that would involve you typing **many** more. I don't think either of us want that.

**Comment by remy** [comment]
I'm afraid a 7 character change will always be way less than the sum character of it going live.

I'm genuinely happy to help you get this in. But it needs both of us to give a little more time. And this way, you'll have a few more tools to your skills to make other projects better in the future.


Your call.

**Comment by alice0meta** [comment]
I understand that the maintainers of nodemon do not and will not support languages other than English.

**Comment by remy** [comment]
Not sure if that repeat message was a mistake or intentional, but to clarify, I am the maintainer and I will support non-english users. 

Do you want to help achieve that? https://github.com/remy/nodemon/pull/787#issuecomment-188674117

Or not? It's you call.

**Comment by alice0meta** [comment]
Thank you for confirming that you will support non-english users. I'll check back in a week to see if the regex has been replaced.

**Comment by remy** [comment]
So I'm clear, are you interested in my helping you, as per https://github.com/remy/nodemon/pull/787#issuecomment-188672958 or are you saying you not interested and you'd rather someone else do the work instead?

**Comment by alice0meta** [comment]
Incorrect. I've done the work to locate a bug and find the precise fix. I'm interested in the maintainers of nodemon doing the work to interface with their own system to publish the fix.

**Comment by remy** [comment]
Maintainers? You mean, me.

So, you're done, and you want me to finish your work.

And, no, you're not interested in me helping you.

Loud and clear.

**Comment by alice0meta** [comment]
Correct. I've done most of the work, and I'd like you to use your domain-specific knowledge to do the last few keystrokes much more efficiently than I could.

Will nodemon support languages other than English, or won't it? If it won't, I'd like to know already, so that I can abandon it. If it will, then I have nothing else to do here.

**Comment by remy** [comment]
See replies above.

**Comment by remy** [comment]
Locking conversation now because you seem to have dropped into an infinite loop.

**Pull request closed without merging**
