### PR TITLE
fix: support windows by using path.delimiter

### PR DESCRIPTION
**Pull request by stijnherreman**
Fixes: #1951

This change was suggested in https://github.com/remy/nodemon/issues/1951#issuecomment-1003362605 and I've verified it fixes the issue.

### CODE REVIEW

**Comment by cwadrupldijjit** [comment]
Ping @remy.  This seems to be a sane way to fix the problem and all of the tests pass.  Any chance that this could get merged in and released?

**Comment by remy** [comment]
sorry for delay - "life" getting in the way - thank you for this 👍

**Review by spazmodius — COMMENTED** [review]
Shouldn't we use OS-sensitive path separators, too?

```suggestion
const binPath = path.join(process.cwd(), 'node_modules', '.bin');
```

**Comment by stijnherreman** [comment]
@spazmodius Yes, that change makes sense. Fortunately forward slashes are accepted on Windows, so the current implementation works too.

**Pull request merged**
