### PR TITLE
Watch cjs modules by default

### PR DESCRIPTION
**Pull request by lorand-horvath**
https://github.com/remy/nodemon/issues/1954

### CODE REVIEW

**Comment by Justman10000** [comment]
@remy

**Comment by remy** [comment]
I'm worried this change looks simple but possibly hiding impact, such as on people's defaults or on what happens ordinarily without it. 

I don't have the time ATM to give it a good test, but it's obviously easy to add this to your own projects to work around it.

**Comment by remy** [comment]
I've moved this in to the latest release. It _should_ be nodemon@3.

**Comment by lorand-horvath** [comment]
@remy Sorry for having to say this upfront, but I was very much expecting for you to actually merge my PR, which was waiting for you to make up your mind and include *.cjs files as default watch since November 2022. For some reason you refused initially, but now all of a sudden it's fine to use it. Instead of pulling in and linking my PR, all you did was thank me with a general @ in your commit https://github.com/remy/nodemon/commit/86d5f403a3e06e8aed48b37fa854730dc83257be which will be untraceable within a few days already.

I know it's not a big deal, but that's not how open source acknowledgements are normally carried out and I think it discourages people from collaborating or supporting each other.

I will completely uninstall nodemon from my dev machines at this point and just use node 18 --watch mode. I strongly urge others to do the same.

**Comment by remy** [comment]
It wasn't really *all of a sudden*! But it was because it was barely a change. The actual work, that you didn't do in the pr, which is why I was wary, was the testing. 

This is what I did on Friday, I created a series of simple test cases and ran them against the change.

It's always the tests that show the work.

But, please do uninstall nodemon. Using node 18's native watch gets you pretty far, I'm sure it'll serve you well (and do share the word about nodes native reload, it helps others so that's not a bad thing).

Hopefully that helps you understand where the real work was, and why I wasn't sure whether it was a safe pr to merge (without having to do the leg work myself back in Novem).

**Comment by remy** [comment]
For what it's worth, I didn't manage to fully test this (because I don't use typescript at all), someone caught that it broke default watching for TS: https://github.com/remy/nodemon/issues/2124

So I baked the cjs watching directly into the code, seen here: https://github.com/remy/nodemon/commit/95bee008bfb4eb77d7826f193e9386812652f449#diff-d649d3b2f2afcc1dfc4d0dce7c28b4fc296860b45dd38d3c7bb0274a6be73708L117 (and then of course tested again)

**Pull request closed without merging**
