### PR TITLE
WIP: working with tests stability

### PR DESCRIPTION
**Pull request by markelog**
Includes commits from some other open pulls, I think you can it's obvious where I am going with this

### CODE REVIEW

**Comment by markelog** [comment]
Look at that, travis is green, still need to implement proper server clean-up, remove warnings in latest node, clean git history, rebase with master.

But before next iteration it would be cool to have a feedback in case i'm not going in the right direction

**Comment by remy** [comment]
What was the change that caused them all to start passing? I'm always wary
that I cant see all the tests (there's about 100 instead of 200…but I could
be wrong, viewing on my mobile ATM).

Also, can you follow the commit message format for all commits so that the
release and notes get generated properly (can't remember if the format is
specified anywhere - again, on mobile).

**Comment by markelog** [comment]
> What was the change that caused them all to start passing?

Some of them weren't cleaned properly i.e. in `After`/`AfterEach` some of them still are, those are currently skipped and I also started to divide them on `unit` and `integration` tests, that also helps. 

By no way I'm finished with this, but before I go further with this, it would be cool if you would give me a green light on continuing, so I would know if i'm going in the right direction, so this approach would adhere to you preferences.

> Also, can you follow the commit message format for all commits so that the
release and notes get generated properly (can't remember if the format is
specified anywhere - again, on mobile).

After i'm finish with it, I'm gonna squash, format, rebase and stuff, right now it's a WIP

**Comment by remy** [comment]
Okay, everything in this PR looks legit to me 👍 good work. 

Happy for it to be squash/merged too (though I notice that the signal config has slipped in as a feature inside of the test tidy up, I don't mind, but if that's in a single commit, that would be great).

I assume these skipped tests are being tracked and can be restored once the test tidy up is further along (though the fact that it passed first time is a big step forward).

I also see you've managed to ditch my hack to run each test file individually - good work (I've long moved over to tap for testing, but I think it would be more work than it would be worth to convert all these tests away from mocha…just a side note!)

**Comment by remy** [comment]
Ping me on this thread when you're ready to merge (and I can quickly review).

**Comment by markelog** [comment]
Sounds good, meanwhile status update:
there is no more skipped tests anymore, had to remove one flacky one though, since it was unstable on systems with limited resources.

As a bonus there is no more ghost test files anymore after tests are executed and there is no more global mocha timeout, plus test clean-up now should be more stable.

There is still four issues that I would like to finish working on here:
1. Right now ghost test files will be removed if test run is not killed forcefully - i.e. if there is no terminate signals during test execution
2. In some situations (TBD) ghost httpd servers are left after test execution 
3. Need to do general cleaning squash and stuff
4. Would like to address https://github.com/remy/nodemon/issues/988 here also

Probably gonna do this in the next weekend, hopefully. Will ping you up as soon as I'm done. 

As a side note: I noticed sometimes code-style is inconsistent, i.e. https://github.com/remy/nodemon/issues/983 issue, I have couple ideas what code-style we can use and I probably can implement it

**Comment by markelog** [comment]
Working on 1,2 items (mentioned above), still need to finish up: generalize & simplify the solution. Will try to work on this during the weekdays also, to speed things up

**Comment by remy** [comment]
👍

**Comment by remy** [comment]
First of all: ❤️ for all your hard work. 

I've recently pushed a load of changes to deps and updated the base level support for nodemon to match LTS node releases (which helps tests a lot since things like 0.10 are dropped).

I'm going to close this PR as the last series of test runs have all passed (when they should have) rather than breaking due to random race conditions (though…I'm not 100% certain they're all gone, but it's much better now).

Thank you again.

**Comment by markelog** [comment]
No worries! And sorry I couldn't finish it, was feeling guilty about this :/

**Pull request closed without merging**
