### PR TITLE
fix: JSON extension not watched outside of coffeescript

### PR DESCRIPTION
**Pull request by pensierinmusica**
Fix a bug that caused `.json` file to not be watched outside of a coffeescript environment,
and improves the extension formatting regex.

### CODE REVIEW

**Comment by pensierinmusica** [comment]
Hi @remy, I just realized my previous commit didn't do anything outside of a CoffeeScript environment. So I fixed it. I'm really sorry about it, I should have noticed it before submitting the PR.

To make it up a bit, I took a chance to improve the regex formatting the extensions string, which allows to shave off ~ lines of code, and seems more reliable to me now.

**Comment by remy** [comment]
Okay, this needs tests. My gut told me the first PR should have had tests, this one definitely does! :)

I've got a few minutes during my lunch, so I might have a go at parring it down.

**Comment by pensierinmusica** [comment]
That would be great, thanks!  :)

**Comment by pensierinmusica** [comment]
Hi @remy! I imagine you're busy these days, do you have any update / timeline in mind for this? Thanks, cheers!

**Comment by pensierinmusica** [comment]
Hi @remy, any updates on this? Cheers!

**Comment by remy** [comment]
Sorry, dropped the ball on this. As usual, family came ahead of bugs. Can
you go ahead and have a crack at adding tests to check this. I don't want
to merge new code without new tests. Cheers.

**Comment by pensierinmusica** [comment]
Hi @remy, why was this closed? The issue is still there, I'll send a PR as soon as I have a sec. Else, if you have a few free minutes and wnat to go ahead with the tests feel free to do it. Btw, the code has been working fine for about  a month now.

**Comment by remy** [comment]
Yeah, not sure why the PR closed, but the outstanding work was the missing
tests. I didn't have the chance in the end, kids took priority.

**Comment by pensierinmusica** [comment]
Not sure, GitHub says (here above) that you closed this PR. Anyways, I'll open a new one. I looked into the tests, and currently Nodemon doesn't have any tests for file changes in other extensions but js. Also it doesn't make any sense to have merged #644 and then not merge this one which actually fixes a bug present in #644. Please take a look at the code yourself for a second in the new PR I'll send, you'll see it's all very reasonable, besides passing all current tests and not introducing anything new apart from detecting changes from JSON files by default.

**Pull request closed without merging**
