### PR TITLE
feat: support --env-file command line arg

### PR DESCRIPTION
**Pull request by mettjus**
Refers to issue #878. Should be working fine. Must I create tests for this one?

### CODE REVIEW

**Comment by remy** [comment]
I'm not super keen on this adding new arguments.

I do understand the need for injecting environment values (and although this can be done in `nodemon.json` I appreciate it's not straight forward).

On tests: yes, you would. But I'm wondering if there's something smarter that can be done here. Perhaps pointing the `env` property to the file and supporting on the CLI (going against my rule of not adding new CLI args).

**Comment by mettjus** [comment]
> On tests: yes, you would.

Ok. I will try to figure them out.

> Perhaps pointing the env property to the file and supporting on the CLI

If you mean add the `env` property to nodemon.json and point it to the .env file I think this would be way more comfortable than the current behaviour but still less than optimal. I say this because I find nodemon incredibly useful to quickly start watching some files without the need of configuration and requiring to create a nodemon.json just to specify the .env file location would look useless setup overhead to me.

**Comment by remy** [comment]
>  say this because I find nodemon incredibly useful to quickly start watching some files without the need of configuration and requiring to create a nodemon.json

Absolutely, and part of the design policy (in the application) is that *every* `nodemon.json` config is available via the CLI, so this is where I *would* add the `--env` support on the CLI (since it's currently missing).

**Comment by remy** [comment]
Late to follow up on this, but I'm going to close. Thinking behind it is that the ENV loading should be outside of nodemon (or inside the target).

**Pull request closed without merging**
