### PR TITLE
revert ES6 usage and node version down to 0.10

### PR DESCRIPTION
**Pull request by Noyabronok**
Reverts ES6 changes and removes husky.  Tests pass under Node 4, but fail under 0.10.  At least it installs without errors under node 0.10.

### CODE REVIEW

**Comment by remy** [comment]
Don't remove husky (and don't add your hidden project files). Husky is used to ensure commit messages style which allows for releases.

**Comment by Noyabronok** [comment]
I had to remove husky for `npm install` to work under Node 0.10
I removed the hidden project files from PR

**Comment by heisian** [comment]
wait why are you using Node 0.10?

**Comment by Noyabronok** [comment]
@heisian version was originally 0.8 but I took the liberty to specify and test under 0.10.  Even with 0.10 tests are failing, but at least `npm install` succeeds.  There is [another PR](https://github.com/remy/nodemon/pull/1149) with Node 4 that has test passing

**Comment by heisian** [comment]
yeah, but... why? are you restricted to using a version that was release 3 years ago and has since been superseded by not only a stable non-alpha/beta release (1.0) and on top of that **8 other versions**??

**Comment by Noyabronok** [comment]
@heisian Please see https://github.com/remy/nodemon/issues/1144 for reasons for these PRs

**Comment by heisian** [comment]
I read that PR, you're listing v0.10 and v4, and trying to implement both, when clearly v4 is really the only sensible option, if at all...

**Comment by Noyabronok** [comment]
@heisian  I was asking @remy to pick the PR he prefers.  Node v4 works for me, and there's no reason that I see that it shouldn't. If nodemon doesn't work at all on 0.10 then we don't need that PR.

In general, the major node version in package.json should not change for a minor nodemon update.  A major version bump is warranted.  What I think should happen:

1) specify node v4 on master branch.  Bump up nodemon version to 2.0
2) if nodemon works on 0.10 - specify node 0.10 on a maintenance branch.  Bump current nodemon version at 1.13.x.

**Comment by heisian** [comment]
@Noyabronok seems like a lot of trouble. i would just fork in this situation, or really just upgrade my node. but to each their own!

**Comment by Noyabronok** [comment]
@heisian you gotta remember that not everyone has the luxury of updating their node version.  That's why it's important to support the node version specified in package.json, and to change nodemon's major version when removing support for older node version

**Comment by remy** [comment]
Node 0.10 failing. Do you want to try to fix these or just close the PR and stick with node 4? @Noyabronok: Your call.

**Comment by Noyabronok** [comment]
@remy Yeah, this is what I was talking about.  I made enough changes for install to work under 0.10 but tests fail.  If someone has a need for 0.10 or 0.8 they can pick up from here, so we can close this PR for now.  Let's stick win Node 4 for simplicity, since that's all I need right now.

**Pull request closed without merging**
