### PR TITLE
Added "clear" command

### PR DESCRIPTION
**Pull request by KlaussMC**
Simply type "clear" into the terminal and the screen will be cleared.

### CODE REVIEW

**Comment by remy** [comment]
Why not just hit ctrl+l?

**Comment by KlaussMC** [comment]
Dear Remy Sharp

I Didn't know that was a thing, also I have never successfully contributed
to an open source project. This is a first for me and it was a feature that
I find quite handy.

Sincerely Jacob

**Comment by KlaussMC** [comment]
I Didn't know that was a thing, also I have never successfully contributed
to an open source project. This is a first for me and it was a feature that
I find quite handy.

not to mention that it's cool AF for no other reason than being able to say *I made an edit to this awesome project that is really damn famous and useful.*

**Comment by remy** [comment]
`ctrl+l` is a standard method to clear all terminal output (including things like your browser's console). It actually doesn't work in nodemon's output because nodemon isn't looking for that on `stdin`.

I think it makes sense to support `ctrl+l` in nodemon. However, the changes you've submitted don't actually do anything. Best case (that I can gather from your change) is that it will automatically clear the console when nodemon starts for the first time. It's not reading from stdin (which is suggested in the readme change), and it's currently failing tests - all reasons that I have to close this PR (sorry - as much as I love contributions, I do need to make sure changes are thorough).

Thanks so much for your contribution all the same.

**Comment by KlaussMC** [comment]
It works for me, I am using it as we speak

just type clear into it, has to be lowercase

**Pull request closed without merging**
