### PR TITLE
Fixed watch count when using fs.watch/watchFile

### PR DESCRIPTION
**Pull request by remy**
A bit donkey, but it works :-\

### CODE REVIEW

**Comment by AsaAyers** [comment]
I found this issue because I'm trying to use nodemon and it's giving me a false warnings about watching 52,721 files. After poking around with `--ignore` and `--watch`, and using verbose it says it's watching the right files and ignoring the right files. I removed the " | wc" in `showWatchCount`, logged stdout of the command and found that it's still counting `node_modules`.

Based on this PR I also started logging `watchers.length` to verify that I'ts actually watching 199 files.

```
13 Jan 14:57:42 - [nodemon] v1.2.1
13 Jan 14:57:42 - [nodemon] reading config /home/asa/repos/my_project/nodemon.json
13 Jan 14:57:42 - [nodemon] to restart at any time, enter `rs`
13 Jan 14:57:42 - [nodemon] ignoring: /home/asa/repos/my_project/.git/**/* /home/asa/repos/my_project/node_modules/**/* bower_components .sass-cache
13 Jan 14:57:42 - [nodemon] watching: *.*
13 Jan 14:57:42 - [nodemon] watching extensions: js,jsx,coffee
13 Jan 14:57:42 - [nodemon] starting `npm test`
13 Jan 14:57:42 - [nodemon] child pid: 6601

... snip ...

13 Jan 14:57:43 - [nodemon] watching 52,721 files
13 Jan 14:57:43 - [nodemon] watching 52,721 files - this might cause high cpu usage. To reduce use "--watch".

... snip ...

Run time: 1.335s
13 Jan 14:57:44 - [nodemon] clean exit - waiting for changes before restart
```

**Comment by remy** [comment]
@AsaAyers can you try the version that's in github right now - I believe it has the watch count fix in it.

**Comment by AsaAyers** [comment]
You're correct, `master` is not producing a warning about the number of files being watched.

**Comment by remy** [comment]
That's great. I'll try to rebase this branch so it's passing tests again, and you'll see the 1.3.x release very soon.

**Comment by remy** [comment]
Closing in favour of #625.

**Pull request closed without merging**
