### PR TITLE
Add .json to default watched file extensions

### LINKED ISSUE #643: Detect changes in JSON files
Hi,

I'm using `nodemon` (v1.6.1) with Node (v4.1.0), it works perfectly but it doesn't detect changes in any ".json" files. Is this default behavior? How can it be changed?

Since in a server environment JSON files usually contain some settings, imho nodemon should restart by default when the content of a JSON file is changed.

Looking forward to hear your feedback, thanks!

### PR DESCRIPTION
**Pull request by pensierinmusica**
Closes #643

### CODE REVIEW

**Comment by remy** [comment]
Please update commits as per contributing document.

**Comment by pensierinmusica** [comment]
Done  :)

**Comment by erikzaadi** [comment]
:+1:

**Comment by dvberkel** [comment]
tl;dr; :+1: 

I use `nodemon` only as a development tool, so issue #643 does not apply so directly to me. But when I develop an application I too want to restart on configuration changes.

**Comment by rapzo** [comment]
:+1: 
They can be required and all so they are can be tied to the code. Makes sense to watch them.

**Comment by remy** [comment]
Merged and live in `nodemon@1.7.0`

**Pull request closed without merging**
