### PR TITLE
node 4 min

### PR DESCRIPTION
**Pull request by Noyabronok**
enforce node 4 instead of node 6 as minimum.
all tests pass under node 4

### CODE REVIEW

**Comment by remy** [comment]
Looks good. I'll squash the commits so they follow the right syntax for the commit style (i.e. to allow it to deploy)

**Comment by Noyabronok** [comment]
@remy let's get this PR merged. Thanks!

**Comment by remy** [comment]
Can you merge [this commit](https://github.com/remy/nodemon/commit/8967c02301cbc4f1f0cecab2e192e0ede82463cf) into your branch? It should fix the npm install problem properly now and will allow me to merge without having to edit your code.

**Comment by remy** [comment]
Awesome work.

**Comment by remy** [comment]
Kinda my issue with node 4: https://travis-ci.org/remy/nodemon/builds/315493550 😢

**Comment by remy** [comment]
I know what this is now. Another PR requires node>4 :(

**Comment by Noyabronok** [comment]
what pr is that?  Can it be updated to be compatible with Node 4?

**Comment by remy** [comment]
If you check master out you'll see it failing on the config/env.js test in node 4.

It seems like run.js using fork in node 4 is throwing an exception when it tries to attach `child.stdout.on` but I don't see it in the test so it eventually times out.

**Comment by remy** [comment]
Sorted and live.

**Pull request merged**
